# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: demo_vol
    vol_size: 40

# Security group
security_groups:
  - name: common_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: common_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_express
    description: "Demo security group for Express"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_react
    description: "Demo security group for React"
    protocol: tcp
    port_range_min: 3001
    port_range_max: 3001
    remote_ip_prefix: 0.0.0.0/0


# Instance
instances:
  - name: demo
    volumes: ['demo-vol']
    image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
    key_name: ccckey
    flavor: uom.mse.1c4g
    network: qh2-uom
