---
- name: copy github private key
  copy:
    src: "keys/id_ed25519"
    dest: "/home/ubuntu/.ssh/sshkey"
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: create working directory
  become: yes
  file:
    path: "{{ project_directory }}"
    state: directory

- name: add github.com to known_hosts
  become: yes
  shell: ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts

- name: clone
  become: yes
  shell: git clone git@github.com:Toraycaaa/CCC_Assignment_2.git --config core.sshCommand="ssh -i /home/ubuntu/.ssh/sshkey"
  args:
    chdir: "{{ project_directory }}"
