---
- name: remove previous crawler
  shell: docker-compose down --rmi local
  become: yes
  args:
    chdir: "{{ git_repo_crawler }}"

- name: deploy crawler and run
  become: yes
  shell: docker-compose up --build -d
  args:
    chdir: "{{ git_repo_crawler }}"
