# Volume
volumes:
  - vol_name: couchdb_vol-1
    vol_size: 50
  - vol_name: couchdb_vol-2
    vol_size: 50
  - vol_name: couchdb_vol-3
    vol_size: 50
  - vol_name: data_vol
    vol_size: 350

# Security group
security_groups:
  # Common
  - name: common_ssh
    description: "Common security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: common_http
    description: "Common security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

  # CouchDB
  - name: couch_empd
    description: "CouchDB security group for Erlang port mapper daemon (epmd)"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couch_cluster
    description: "CouchDB security group for standard clustered port for all HTTP API requests"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couch_communication
    description: "CouchDB security group for communication with other nodes"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: 0.0.0.0/0
  - name: couch_empd
    description: "CouchDB security group for Erlang port mapper daemon (epmd)"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couch_cluster
    description: "CouchDB security group for standard clustered port for all HTTP API requests"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couch_communication
    description: "CouchDB security group for communication with other nodes"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9100
    remote_ip_prefix: 0.0.0.0/0

  # Demo
  - name: demo_express
    description: "Demo security group for Express"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_react
    description: "Demo security group for React"
    protocol: tcp
    port_range_min: 3001
    port_range_max: 3001
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: couch_master
    volumes: ["couchdb_vol-1", "data_vol"]
    flavor: uom.mse.2c9g
  - name: couch_slave-1
    volumes: ["couchdb_vol-2"]
    flavor: uom.mse.2c9g
  - name: couch_slave-2
    volumes: ["couchdb_vol-3"]
    flavor: uom.mse.2c9g
  - name: demo
#    volumes: ["demo-vol"]
    flavor: uom.mse.1c4g

# Common Vars
instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: ccckey
instance_network: qh2-uom
availability_zone: melbourne-qh2-uom
