---
# Update and upgrade apt package
- name: Update and upgrade apt package
  become: yes
  apt:
    update_cache: yes
    upgrade: "yes"
# sudo apt-get update && sudo apt-get upgrade -y

- name: Install pip and npm
  become: yes
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python3-pip
    - npm



- name: Install docker dependencies packages
  become: yes
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg 
    - lsb-release

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes 
    name: docker-ce 
    state: latest

- name: Create comp90024 Directory
  file: 
    path: "{{homeDir}}/comp90024"
    state: directory

- name: Git clone repo
  git:
    repo: "https://github.com/AURIN/comp90024.git"
    dest: "{{homeDir}}/comp90024"
  register: git_finished

- name: Running NPM install
  npm: 
    path: "{{homeDir}}/comp90024"
  register: npm_finished
  when: git_finished.changed


