---
- name: Install dependencies
  tags: 'volumes'
  apt:
    name: ['xfsprogs']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Make File Systems
  tags: 'volumes'
  filesystem:
    fstype: xfs
    dev: "{{item.device}}"
  when: item.device is defined
  with_items:
  - "{{ volumes }}"

- debug:
    msg: "{{item}}"
  loop: '{{volumes}}'

- name: Checking folders
  tags: 'volumes'
  stat:
    path: "{{item.mountpoint}}"
  register: directory_stats
  with_items:
  - "{{volumes}}"

- name: Create directory
  tags: 'volumes'
  file:
    path: "{{item.item.mountpoint}}"
    recurse: yes
    state: directory
  when: item.stat.exists == false
  with_items:
  - "{{directory_stats.results}}"

- name: Mount device
  tags: 'volumes'
  mount:
    path: "{{item.mountpoint}}"
    src: "{{item.device}}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  with_items:
  - "{{volumes}}"