---
- name: Update and upgrade apt package
  apt:
    update_cache: yes
    upgrade: "yes"
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update && sudo apt-get upgrade -y

- name: Install nodejs
  apt:
    name: 'nodejs'
    state: latest

- name:  Update npm and Install React and Express
  npm:
    name: "{{item}}"
    global: yes
    state: latest
  with_items:
    - npm
    - create-react-app
    - express

- name: Create APP Directory
  file: 
    path: "{{homeDir}}/{{repo}}"
    state: directory


- name: Git clone repo
  git:
    repo: "git@github.com:Toraycaaa/{{repo}}.git"
    dest: "{{homeDir}}/{{repo}}"
    key_file: "{{homeDir}}/id_rsa"
    clone: yes
    update: yes
  register: git_finished

- name: Running NPM install
  npm: 
    path: "{{homeDir}}/{{repo}}"
  register: npm_finished
  when: git_finished.changed

- name: Start APP
  command: cd {{homeDir}}/{{repo}}/backend && npm start
  ignore_errors: yes
  when: npm_finished.changed

