---
- hosts: crawler
  gather_facts: true
  vars_files:
    - host_vars/config.yaml
  roles:
    - role: deploy-crawler
# Cluster should be deplyed first
# - hosts: masternode
#   vars_files:
#     - host_vars/config.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-couchdb-cluster

#  - hosts: crawler
#    vars_files:
#      - host_vars/config.yaml
#    gather_facts: true
#    roles:
#      - role: git-pull-source-repository
