---
# https://stackoverflow.com/questions/35798101/execute-curl-x-with-ansible-playbook

- name: get hostvars
  debug:
    var: " groups "

- name: setup couchdb cluster 1
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:{{ couchdb_port }}/_cluster_setup
    method: POST
    status_code: 201
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_pass }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    headers:
      Content-Type: "application/json"
    body: "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
      \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_pass }}\", \"port\": \"{{couchdb_port}}\",\
      \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ groups['database'] | length }}\",\
      \"remote_current_user\":\"{{ couchdb_user }}\", \"remote_current_password\":\"{{ couchdb_pass }}\"}"

  loop: "{{ groups['workers'] }}"

- name: setup couchdb cluster 2
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:{{ couchdb_port }}/_cluster_setup
    method: POST
    status_code: 201, 409
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_pass }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"add_node\", \"host\":\"{{ item }}\",\
      \"port\": \"5984\", \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_pass }}\"}"

    headers:
      Content-Type: "application/json"
  loop: "{{ groups['workers'] }}"

- name: This empty request is to avoid an error message when finishing the cluster setup
  uri:
    url: http://{{ groups['masternode'][0] }}:{{ couchdb_port}}/
    method: GET
    status_code: 200, 201
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_pass }}"
    force_basic_auth: yes
    return_content: yes

- name: finish
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:{{ couchdb_port }}/_cluster_setup
    status_code: 200, 201
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_pass }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: '{"action": "finish_cluster"}'
    headers:
      Content-Type: "application/json"

- name: check whether cluster configuration is corret
  become: yes
  uri:
    url: http://{{ item }}:{{ couchdb_port }}/_membership
    method: GET
    status_code: 200, 201
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_pass }}"
    force_basic_auth: yes
    return_content: yes

  loop: "{{ groups['database'] }}"
